### ISSUE TITLE
add ability to have a placeholder message for a non-yet implemented table

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#109] opened 2018-08-28 13:12 UTC
From comments in #70, there are a number of irregular Latin verbs for which we don't currently have inflection table data.  @monzug asks: can we add the verb irregular from drop-down for all irregular verbs and if inflection table is not available, a message pops up saying that table is not available yet?

@kirlat I'm not sure how difficult this would be to implement. What are your thoughts?

**Comment by kirlat** [comment] 2018-08-28 13:41
@balmas, we check if a verb is irregular by comparing it against a list of known irregular verb forms: https://github.com/alpheios-project/inflection-tables/blob/master/lib/lang/latin/latin-language-dataset.js#L434-L439. So if it is some verb unknown to us how do we know if it is irregular?

But if we could get a list of those "unimplemented" irregular verbs, they can be matched against an irregular verb view (so that this view be shown in a list of views available) and we can set a `notImplemented` flag on the view. Then a Vue.js component can show a special message for such views. Should be pretty straightforward to do then.

**Comment by balmas** [comment] 2018-08-28 13:51
@kirlat We now set the conjugation Feature on irregular Latin verbs to Constants.type.IRREGULAR so we could add that in the checkIrregularVerb test . So it sounds like this should be pretty easy so let's go ahead and do it. That way we can postpone adding some of these tables until the next release.

**Comment by monzug** [comment] 2018-08-29 13:56
sure.
inquam is a good example for the 7th conjugation,  queo for 6th conjugation
and absum for 5th conjugation

inqu.am              V      7 2 PRES ACTIVE  IND 1 S
inquiam, -, -  V   [XXXAX]
say (defective); (postpositive - for direct quote); [inquiens -> saying];
que.o                V      6 1 PRES ACTIVE  IND 1 S
queo, quire, quivi(ii), quitus  V   [XXXBX]
be able;
abs.um               V      5 1 PRES ACTIVE  IND 1 S
absum, abesse, abfui, abfuturus  V   [XXXDS]    lesser
absum, abesse, afui, afuturus  V   [XXXAO]
be away/absent/distant/missing; be free/removed from; be lacking; be
distinct;

**Comment by monzug** [comment] 2018-08-29 13:58
let me know if you need more examples.

**Comment by kirlat** [comment] 2018-08-30 13:31
Thanks, those two are perfect test cases. They made me quite happy!

**Comment by kirlat** [comment] 2018-08-30 16:38
I've made a fix within the `infltbl-i109` branch. Here is a link to download a test version of webextension: https://github.com/alpheios-project/webextension/archive/infltbl-i109.zip. 
Please let me know if you will have any questions or issues. Thanks!

**Comment by monzug** [comment] 2018-08-30 16:45
perfect - will try tomorrow morning. Thanks!

**Comment by monzug** [comment] 2018-08-31 08:03
Kirlat, I just installed the build on Chrome and got the message: THIS
TABLE HAS NOT BEEN IMPLEMENTED YET
1) could you please change the font to the standard used in Option panel
(if there is a standard...)
2) it looks like the lookup is sticky to the last inflection table opened
in the case of subii (exception of subivi). it does keep showing the last
inflection table opened (lookup for amat, inflection for amo verb opened,
then enter subii, inflection table for amo is opened again). any idea?

**Comment by monzug** [comment] 2018-08-31 09:52
actually, second issue is related to your build. in the current build
available for testing 2.0.2.3, the verb irregular is not selectable from
drop-down so I cannot test this scenario. will wait for a merge of your fix
to test it again.

**Comment by kirlat** [comment] 2018-08-31 09:54
@monzug, I've updated the build to adjust a font, please check if the current one looks better.

As for the second issue, this is related to previous inflection table not cleared when a new table cannot be constructed (i.e. when there is an error). This should be hopefully fixed with https://github.com/alpheios-project/webextension/archive/comp-i102.zip.

**Comment by kirlat** [comment] 2018-08-31 09:57
There are a couple of fixes I'm working on right now. It's probably better to wait all of them to merge before retesting the second issue as those builds will introduce changes to behavior described.

**Comment by monzug** [comment] 2018-08-31 10:36
perfect. THANKS!!!!

**Comment by monzug** [comment] 2018-08-31 15:09
Kirlat, I did install the build above but the irregular verb are not
available from drop-down so I cannot check for the font.

**Comment by kirlat** [comment] 2018-08-31 15:48
Monica, if you installed comp-i102 then that's for a different issue, can you please try https://github.com/alpheios-project/webextension/archive/infltbl-i109.zip to check the font. I've updated this build with new font rules.

**Comment by monzug** [comment] 2018-08-31 17:57
Looks good. Thanks.
let me know when the fix for subii is ready for testing.

**Comment by kirlat** [comment] 2018-09-03 14:45
It is in the other fix package. I think it's probably better to test `master` after all fixes are merged and if the problem is still there, open a new issue. What do you think?

**Comment by monzug** [comment] 2018-09-03 16:04
tested with fix 102. works fine. closed this one.

**Closed by monzug** 2018-09-03 16:04 UTC
Labels: enhancement, waiting_verification
