### ISSUE TITLE
state conflicts with Expand/collapse when browsing the Inflection tables

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#173] opened 2018-09-21 12:50 UTC
the collapse/expand tooltip is misleading when browsing the Inflection tables.
let's say I lookup for pulcher and go to the related adj table. from there I can browse through the Latin tables. If I go to the regular verbs, I have the collapse button for voice-mood-conj and the tooltip says to collapse the column with matching endings but we do not have any matching endings here.
Note that conj-voice-mood and conj-mood-voice do not have the button available.
Options:
1) suppress the button also for the other 4 views
2) update the tooltip for this specific situation

**Comment by balmas** [comment] 2018-09-21 13:34
hmm. Having trouble reproducing this. I am not getting the expand button on the latin verb tables in this scenario. I looked up pulcher, then browsed the latin irregular tables, no button. 
![screenshot from 2018-09-21 09-32-51](https://user-images.githubusercontent.com/644870/45884220-576d1e80-bd81-11e8-8358-2260321c775e.png)

Am wondering if this is another issue related to shared  state between the query table and the browsing table. Maybe it depends upon whether you've previously looked up a verb that does collapse the tables? @monzug can you stlil reproduce?

**Comment by monzug** [comment] 2018-09-21 13:43
let me try in clean environment. of course, testing the browser, I have
opened tons of verb tables.

**Comment by monzug** [comment] 2018-09-21 13:47
you are right.  in clean environment (starting from scratch with first
lookup pulcher) buttons are not there. this has been driving me crazy since
yesterday. I did also ask @kirlat for more explanation on button
functionality. so it does happen frequently.

**Comment by balmas** [comment] 2018-09-21 13:51
@kirlat it seems that state of expand/collapse is being shared across the lexical query and standard form instances of the latin regular verb views

**Comment by kirlat** [comment] 2018-09-21 14:40
@balmas, I think this is a side effect of a collapse/expand button merge. I believe inflection browser tables should always display expanded (because they display no suffix matches), and they should not display a collapse/expand button. Do you agree? If you do, I will remove a button for all inflection browser tables.

**Comment by balmas** [comment] 2018-09-21 14:41
yes I agree.

**Comment by kirlat** [comment] 2018-09-21 15:02
https://github.com/alpheios-project/webextension/archive/infltbl-i173.zip: this should do it.

**Comment by balmas** [comment] 2018-09-21 15:13
@kirlat this change looks fine to me. Please just go ahead and merge it to master. Thank you! (Monica is in transit right now and won't test this herself until later...)

**Comment by kirlat** [comment] 2018-09-21 16:02
Has been merged into master

**Comment by monzug** [comment] 2018-09-22 14:36
buttons have been removed from latin verb tables in browser view. Thanks

**Closed** 2018-10-08 21:40 UTC
Labels: bug, verified
