### ISSUE TITLE
exact match not taking all lexemes into account?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/inflection-tables#167] opened 2018-09-20 13:59 UTC
take the case of `venit`

this has two possible verb lexemes, 

venio, for which the suffix is -it and it should find an exact match in the 3rd person s pres ind active column
veneo, an irregular verb for which the suffix is -t and there is no exact match

Are we missing the exact match on ven-it because of the 2nd verb?

**Comment by balmas** [comment] 2018-09-20 14:04
see also #168 which is another bug which seems to be caused by multiple lexemes with same pofs

**Comment by kirlat** [comment] 2018-09-24 09:53
I think I found some issues with the code that might take effect in tricky cases like that. I will try to eliminate them and hopefully, it will solve, or at least explain behavior in this case. I hope it will have a positive effect on other similar cases too.

**Comment by kirlat** [comment] 2018-09-25 12:41
Submitted a fix for this, https://github.com/alpheios-project/webextension/archive/infltbl-i167.zip, Please verify if it is working as expected. 

In order to fix it, I had to make changes that affected other tables as well, so it would be good to test them too. I did my tests, and it seemed OK to me, but I might miss something. 

As a result of those fixes, it seems that we are getting more full matches now, but those seems legitimate to me. Please let me know what do you think. Thanks!

**Comment by monzug** [comment] 2018-09-25 15:58
tested for few verbs such as vincit, cepit, venit, eo, odi, reperri, scrutato, excruciato.
@kirlat, could you pls tell me which other tables are affected by this change so I can test more broadly? Thanks

**Comment by balmas** [comment] 2018-09-25 16:01
@kirlat please also go ahead and issue a PR for this and #168. Thank you!

**Comment by kirlat** [comment] 2018-09-25 16:19
@monzug, unfortunately, all of them potentially are. Changes were made to the part that was storing information about matches within inflection tables. The goal was to eliminate a possibility of one inflection erasing some match data of the other inflection of the same part of speech. So probably the ones where it would make a real difference are those where we have two inflections of the same part of speech but with different characteristic (e.g. regular and irregular verbs). Probably we'll have more exact matches in such cases now.

**Comment by balmas** [comment] 2018-09-25 17:41
this is now in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-14/dist

**Comment by monzug** [comment] 2018-09-26 10:07
eo is a good example of irregular and regular verb and we do have exact matches.

**Comment by monzug** [comment] 2018-09-26 10:28
lookup for latum: why do we have all these cells highlighted? all the singular in the irregulat conj. + all cells in the participle irregular - see screenshot

![cell-highlighted](https://user-images.githubusercontent.com/41396793/46074260-0da38000-c155-11e8-89d9-280a64a5d606.JPG)

**Comment by monzug** [comment] 2018-09-26 10:41
for latum, I have the adj, supine and verb participle. the drop-down for the supine has the supine regular table and the irregular table. if I open the supine irregular table, I do also have two collapsed tables; conjugation irregular and the verb participle irregular. Note that the verb participle does not have these collapsed tables. see screenshot

![supine-irregular](https://user-images.githubusercontent.com/41396793/46074854-c0c0a900-c156-11e8-9af1-e913b0164ccf.JPG)

why do we have these tables for the supine irregular? if it's ok to display them, shouldn't we have the same option for the participle?

**Comment by balmas** [comment] 2018-09-26 11:12
Hmm. It seems somehow some of the the changes in #76 were undone.

**Comment by balmas** [comment] 2018-09-26 11:14
I am wondering too if we should suppress morphology matches in the linked tables. I think the problem with the extra cells is that the morphology is the wrong morphology because it is for a different part of speech (i..e supine vs regular verb).  At this stage though, maybe the simpler option would be to remove the linked tables and add them back for the next release.  @monzug what do you think?

**Comment by monzug** [comment] 2018-09-26 11:38
@balmas, can we have @kirlat to check first if this can be a side effect of this fix? he said that we should get more cells highlighted.

**Comment by kirlat** [comment] 2018-09-26 15:08
https://github.com/alpheios-project/webextension/archive/infltbl-i167.zip should disable morphology matching highlighting for all linked tables

**Comment by monzug** [comment] 2018-09-26 15:19
ok but not quite right yet. we still have the cells highlighted for dative
and ablative in the supine irregular table and  the cell for the ablative
in the supine regular table.
lat.um               SUPINE 3 2 *ACC S* N

**Comment by kirlat** [comment] 2018-09-26 16:58
I've added case to the list of comparison features for morphology matches of irregular verb forms. It should fix the case with extra incorrect matches in supine tables. Download link is the same: https://github.com/alpheios-project/webextension/archive/infltbl-i167.zip.

**Comment by balmas** [comment] 2018-09-26 20:07
I have merged this to master now and made it available for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-15/dist

**Comment by monzug** [comment] 2018-09-27 09:44
@kirlat. one more: laturus is only verb participle. why do we show the supine table?
see screenshot

![laturus](https://user-images.githubusercontent.com/41396793/46137771-507a5c00-c218-11e8-8962-addf56ac0267.JPG)

**Comment by monzug** [comment] 2018-09-27 10:04
@balmas is it ok for you?

**Comment by kirlat** [comment] 2018-09-27 11:50
@monzug, my understanding was that for each irregular verb table we need to show tables for other forms too. So if it's an irregular verb, we show participle and supine tables as well. Similarly, for participles we show verb and supine tables too. So that's by design.

If this is incorrect, we can change that easily. We have a list of "linked" tables for every such view. Removing supine table from a linked tables list for participle would make it show only a verb table in addition to the main (participle) one. Would that be correct? Would that change (i.e. removal of a linked supine table) apply to every irregular participle in Latin?

Please let me know. I can do this change easily.

**Comment by monzug** [comment] 2018-09-27 12:28
I am fine with it. I just want to make sure that we are all on the same
page. @balmas ?

**Comment by balmas** [comment] 2018-09-27 12:35
yes, that was what I requested.

**Comment by monzug** [comment] 2018-09-27 12:40
perfect!

**Comment by kirlat** [comment] 2018-09-27 12:58
Please review an updated build with linked supine tables removed from verb participle views: https://github.com/alpheios-project/webextension/archive/infltbl-i167.zip.

If it is working fine, I will issue a PR and merge it into `master`.

**Comment by balmas** [comment] 2018-09-27 13:02
@kirlat sorry if it wasn't clear -- I think we are fine with the supine tables being there.

**Closed** 2018-10-08 21:40 UTC
Labels: bug, verified
