### ISSUE TITLE
Greek verb browser: sub tables missing

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#235] opened 2018-10-31 12:46 UTC
we are still missing the sub tables for the Perfect Active System in the verb browser:
optative (simple)    optative (periphrastic)    imperative
for the Future System (without contraction): 
passive indic.   passive opt.
for the Perfect System Middle-Passive: indicative, infinitive, participle:
velar plosive stem    stem in λ     stem in ν
that should be all, hopefully

**Comment by balmas** [comment] 2018-10-31 13:51
All of the subtables are still missing from the browser. There are many tables this is the case for the infinitive and participle. I was able to fix the Pluperfect Middle-Passive Indicative by just merging the subtables in the main table, but that won't work as well for the rest. This requires a bigger fix that I would like to postpone for later. It's too much to include in a patch release.

**Comment by balmas** [comment] 2020-01-15 21:11
I think this is a dupe of #225

**Closed** 2020-01-15 21:11 UTC
Labels: bug, duplicate
