### ISSUE TITLE
on Firefox, extension is deactivated when scrolling grammar

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#141] opened 2018-09-05 15:30 UTC
tested on latest build 2.0.2.4 on Firefox.
not sure if this is a side effect of all recent changes or it has always been there.
when scrolling the grammar after a reload, the extension is turned off (icon is grey and not blue).
the functionality is there and the icon is turned on as soon as I moved away from the grammar.

**Comment by balmas** [comment] 2018-09-05 17:46
oh that's weird. Will investigate.

**Comment by monzug** [comment] 2018-09-06 16:52
tested in Chrome and this does not happen. reinstall the new build in
firefox and confirm that the extension goes grey when scrolling the grammar
(follow steps as per above description)

**Comment by balmas** [comment] 2018-09-06 19:28
wow this was a difficult bug to track down.  I believe the cause is that Firefox resets the title and icon for the extension whenever the user navigates to a new page, even when that navigation event occurs inside a frame in the page. We update the webextension state, including the icon, whenever the user navigates to a new page in a tab the main browser window, but we don't want to do that when they navigate in one of the embedded frames. So we apparently need to add an extra test just to make sure the icon is updated when the user navigates within an iframe.

**Comment by balmas** [comment] 2018-09-06 19:32
I'm closing this item here and moving it to the webextension repo.

**Closed by balmas** 2018-09-06 19:32 UTC
Labels: bug

**Comment by monzug** [comment] 2018-09-12 12:38
testes on Firefox, latest build 2.0.4-5
the webextension does still toggle between on/off when going to any section of the grammar. it's so fast that you can barely notice it. I would say it's a go. Bridget?

**Comment by balmas** [comment] 2018-09-12 12:41
yes, I can't really find any way around that with the current architecture. If/when we can drop use of iframes for the grammar we can do this better, but right now, it's about the best I can achieve.

**Comment by balmas** [comment] 2018-09-12 12:42
(I will enter an longer term issue to eliminate iframes in the UI)
