### ISSUE TITLE
esto, Latin verb, does not have any match

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#208] opened 2018-10-05 09:52 UTC
lookup for esto. we do not have a match in the Imperative table, not even a cell highlighted. This can be explain by the fact that we do not have yet the irregular imperative table. Are we going to add the Imperative irregular table?

from Whitaker:
esto
es.to                V      7 3 FUT  ACTIVE  IMP 2 S      Early   
es.to                V      7 3 FUT  ACTIVE  IMP 3 S      Early   
edo, esse, -, -  V   [XXXAO]  
eat; consume, devour; spend money on food; destroy;
.esto                V      5 1 FUT  ACTIVE  IMP 2 S    
.esto                V      5 1 FUT  ACTIVE  IMP 3 S    
sum, esse, fui, futurus  V   [XXXAX]  
to be, exist; also used to form verb perfect passive tenses with NOM PERF PPL

**Comment by monzug** [comment] 2018-11-14 15:35
assign to myself to add imperative tables

**Comment by balmas** [comment] 2020-02-10 16:13
closing as dupe of alpheios-project/alpheios-core#26

**Closed** 2020-02-10 16:13 UTC
Labels: duplicate, question
