### ISSUE TITLE
Latin irregular verbs tables: few changes

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#265] opened 2019-04-30 15:13 UTC
to do next in the Latin irregular verbs table: add all missing form for eo + odeo table + remove accent to desum
see #262

**Comment by balmas** [comment] 2020-02-10 16:20
closing as dupe of alpheios-project/alpheios-core#46 and alpheios-project/alpheios-core#47

**Closed by balmas** 2020-02-10 16:20 UTC
