### ISSUE TITLE
Can we improve double-clicking to include Greek accent?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/inflection-tables#211] opened 2018-10-07 10:17 UTC
Lexical query produces no results for some Greek words with accents. When double-clicking on them, the accent is left out. lookup for these words works fine. Words such as:
οὐδ'
δ' 
πότνι' 
ἀλλ'

**Comment by irina060981** [comment] 2018-10-09 08:08
@monzug and @balmas,
I have made some investigation and the solution is straightforward if to be honest.
The problem is in clearing punctuation method from selection before sending it to Lexical Query.
And `'` is in excluded list.

I think here could be 3 types of solution -

1) to remove `'` from punctuation list for greek language (and then there could be a rare situation when the word is in some quotation)

2) to realise 2 steps:
    a) remove  `'` from punctuation list for greek language
    b) analyze word and try to identify if it is in a quotation or in quotation line/ line's part and remove if it is in quotation

3) to realise 2 steps:
    a) remove  `'` from punctuation list for greek language
    b) to check the word with quotation both variants - with/without in AlpheiosTuftsAdapter

From my point of view - the first variant is quite enough - because it is really difficult to identify where it is accent and where it is quotation.

What do you think?

**Comment by irina060981** [comment] 2018-10-09 08:10
Thank you, Monica!
Now I could reproduce it :)
![image](https://user-images.githubusercontent.com/12377640/46655289-893e0c00-cbee-11e8-801f-97cd3f13860d.png)

**Comment by balmas** [comment] 2018-10-09 13:03
ah that is a little tricky.  I believe it is actually an incorrect usage of the apostrophe in the text because the correct unicode character for this accent is 1fbd (greek koronis). it would work if we looked these words up using the apostrophe because the parser understands the apostrophe to be a transliteration of the greek koronis. But it isn't really valid to use it here.  I'm not sure if want to try to handle this or not.

**Comment by irina060981** [comment] 2018-10-09 13:29
Ok, than I think, I won't change here anything :) I will reassign it back to you, @balmas .

**Comment by balmas** [comment] 2018-10-11 22:06
still thinking on this... it's probably a common enough encoding error that we should try to handle it

**Comment by monzug** [comment] 2018-10-12 05:12
yes. thanks

**Comment by balmas** [comment] 2018-10-18 15:47
ok this will be handled via alpheios-project/data-models#61 . Matching should be retested after that is fixed so leaving this open for now.

**Comment by balmas** [comment] 2018-10-22 19:19
can be tested in https://github.com/alpheios-project/webextension/tree/v2.0.3.1/dist

**Comment by monzug** [comment] 2018-10-24 16:21
yeahhhh, it works so well.  in Homerus there are many  δ'  
will do more testing with accents

**Comment by monzug** [comment] 2018-10-25 10:41
Argh, I close this tab by mistake and lost the list of words that have a morphology output now with this fix. 
I did compare words with accents in build without this fix and in the new build with the fix...so many improvements.
e.g.  ἀμφ'   ἔπειτ'   ἄγεθ'  ἠμείβετ'

**Closed** 2018-11-14 15:56 UTC
Labels: verified
