### ISSUE TITLE
intersum, desum - Latin Irregular Verb is not shown

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/inflection-tables#311] opened 2019-12-10 12:20 UTC
Working on - https://github.com/alpheios-project/inflection-tables/issues/289

**intersum**  

It is defined as irregular from morph service
![image](https://user-images.githubusercontent.com/12377640/70528834-da52e280-1b9a-11ea-92d0-cf741f4b780b.png)

It has data in inflections forms as irregular
but it is shown as not implemented

![image](https://user-images.githubusercontent.com/12377640/70528899-01111900-1b9b-11ea-9059-f38909496bd4.png)

@balmas , I decided to post this issue not to loose it

**Comment by irina060981** [comment] 2019-12-10 12:22
desum
![image](https://user-images.githubusercontent.com/12377640/70529086-767ce980-1b9b-11ea-897e-f08cd9a89de6.png)

![image](https://user-images.githubusercontent.com/12377640/70529104-7d0b6100-1b9b-11ea-9b28-5a59f0288c1c.png)

**Comment by balmas** [comment] 2019-12-10 18:20
The issue with desum is probably a dupe of #259
The issue with intersum could be a dupe of #150

**Comment by irina060981** [comment] 2019-12-11 08:01
And I believe this closed too
https://github.com/alpheios-project/inflection-tables/issues/276

**Closed** 2020-01-15 20:21 UTC
Labels: duplicate
